---
- name: clear default timezone
  file: path=/etc/localtime
        state=absent


- name: set timezone
  copy: content='{{ timezone }}'
        dest=/etc/timezone
        owner=root
        group=root
        mode=0644


- name: update hardware clock
  command: dpkg-reconfigure -f noninteractive tzdata
